### PR TITLE
Add Linux support

### PR DESCRIPTION
**Pull request by medusalix**
- [x] Audio sessions
- [x] Build scripts
- [x] README (including build scripts)

A couple of notes:

- The Linux implementation of `go-serial` requires either `InterCharacterTimeout` or `MinimumReadSize` to be set to a value other than zero (see [this](https://github.com/jacobsa/go-serial/blob/15cf729a72d49e837fa047a4142fa6e4d5ab45a1/serial/serial.go#L91)). I've decided to set `MinimumReadSize` to `1`, although that seems to be used as a timeout in the Windows implementation (WHY?!, see [here](https://github.com/jacobsa/go-serial/blob/15cf729a72d49e837fa047a4142fa6e4d5ab45a1/serial/open_windows.go#L209)).
- I've had to rename the `rsrc.syso` file to `rsrc_windows.syso` because the Go linker complained.
- I've also removed redundant build constraints from the Windows session implementations. The `_windows` in the filename serves as an implicit build constraint. The icon file had a build constraint too (don't know why), I had to remove it to get the icon to work on Linux.

### CODE REVIEW

**Comment by omriharel** [comment]
Hey @medusalix, I realize you're not done yet but I just wanted to say this looks awesome so far. I really appreciate that you're keeping a consistent code style!

Also cool to learn that the `_windows.go` suffix is an implicit build constraint, I had no idea that was a thing, thank you for pointing that out.

I'm curious, is the byte data for the icons actually displaying properly on Linux? Because it's originally from a .ico file which AFAIK is windows-only. This is used both by `notify` to display system notifications, and by `systray` for the tray icon and menu item icons. 

Another small question is what the Linux equivalent for `rsrc.syso` is, if any - this is what embeds the .ico into the built executable on Windows.

**Comment by medusalix** [comment]
> I'm curious, is the byte data for the icons actually displaying properly on Linux? Because it's originally from a .ico file which AFAIK is windows-only.

I didn't try out the systray because it requires the GTK3 libraries (huge number of packages, around 123 in total) on Linux. For notifications, it seems to be working just fine:

notification

I encountered a bug in the PulseAudio libary while implementing audio sessions (jfreymuth/pulse#16). The author apparently fixed it in the latest version, so I can continue my work now.

**Comment by omriharel** [comment]
Awesome! WRT tray, keep in mind that currently it's the only way to invoke a manual session refresh, other than re-launching.

(A session refresh is triggered automatically under some circumstances, but it's not foolproof. I do want to improve ongoing session management such that this is no longer required, but still haven't figured out a good way)

**Comment by medusalix** [comment]
> Another small question is what the Linux equivalent for rsrc.syso is, if any - this is what embeds the .ico into the built executable on Windows.

AFAIK, there's no way to embed icons into a Linux executable. There are `.desktop` files though, which are kind of similar to shortcuts you put on your desktop on Windows. They usually appear in application menus and you can specify their icon.

**Comment by omriharel** [comment]
Hey @medusalix, just pulled everything locally to make sure nothing broke on Windows and everything is fine!

I did need to update the script paths referred to from `scripts/windows/build-all.bat`, and while I was doing that I figured it would be helpful to make them cwd-independent. I've attached a patch which does this for the Windows scripts, would you kindly `git apply` it?

As for the Linux scripts, leaving it up to your discretion whether you'd like the same for them.

(apparently GitHub won't upload `.patch` files so here it is:)

```diff
diff --git a/scripts/windows/build-all.bat b/scripts/windows/build-all.bat
index 2b76886..9795fee 100644
--- a/scripts/windows/build-all.bat
+++ b/scripts/windows/build-all.bat
@@ -2,5 +2,8 @@
 
 ECHO Building deej (all)...
 
-CALL scripts\build-dev.bat
-CALL scripts\build-release.bat
+REM set windows scripts dir root in relation to script path to avoid cwd dependency
+SET "WIN_SCRIPTS_ROOT=%~dp0"
+
+CALL "%WIN_SCRIPTS_ROOT%build-dev.bat"
+CALL "%WIN_SCRIPTS_ROOT%build-release.bat"
diff --git a/scripts/windows/build-dev.bat b/scripts/windows/build-dev.bat
index eb92a19..3ba5cbc 100644
--- a/scripts/windows/build-dev.bat
+++ b/scripts/windows/build-dev.bat
@@ -4,6 +4,9 @@ IF "%GOPATH%"=="" GOTO NOGO
 
 ECHO Building deej (development)...
 
+REM set repo root in relation to script path to avoid cwd dependency
+SET "DEEJ_ROOT=%~dp0..\.."
+
 REM shove git commit, version tag into env
 for /f "delims=" %%a in ('git rev-list -1 --abbrev-commit HEAD') do @set GIT_COMMIT=%%a
 for /f "delims=" %%a in ('git describe --tags --always') do @set VERSION_TAG=%%a
@@ -13,7 +16,7 @@ ECHO - gitCommit %GIT_COMMIT%
 ECHO - versionTag %VERSION_TAG%
 ECHO - buildType %BUILD_TYPE%
 
-go build -o deej-dev.exe -ldflags "-X main.gitCommit=%GIT_COMMIT% -X main.versionTag=%VERSION_TAG% -X main.buildType=%BUILD_TYPE%" .\cmd
+go build -o "%DEEJ_ROOT%\deej-dev.exe" -ldflags "-X main.gitCommit=%GIT_COMMIT% -X main.versionTag=%VERSION_TAG% -X main.buildType=%BUILD_TYPE%" "%DEEJ_ROOT%\cmd"
 ECHO Done.
 GOTO DONE
 
diff --git a/scripts/windows/build-release.bat b/scripts/windows/build-release.bat
index bcef409..26a32c3 100644
--- a/scripts/windows/build-release.bat
+++ b/scripts/windows/build-release.bat
@@ -4,6 +4,9 @@ IF "%GOPATH%"=="" GOTO NOGO
 
 ECHO Building deej (release)...
 
+REM set repo root in relation to script path to avoid cwd dependency
+SET "DEEJ_ROOT=%~dp0..\.."
+
 REM shove git commit, version tag into env
 for /f "delims=" %%a in ('git rev-list -1 --abbrev-commit HEAD') do @set GIT_COMMIT=%%a
 for /f "delims=" %%a in ('git describe --tags --always') do @set VERSION_TAG=%%a
@@ -13,7 +16,7 @@ ECHO - gitCommit %GIT_COMMIT%
 ECHO - versionTag %VERSION_TAG%
 ECHO - buildType %BUILD_TYPE%
 
-go build -o deej-release.exe -ldflags "-H=windowsgui -s -w -X main.gitCommit=%GIT_COMMIT% -X main.versionTag=%VERSION_TAG% -X main.buildType=%BUILD_TYPE%"  .\cmd
+go build -o "%DEEJ_ROOT%\deej-release.exe" -ldflags "-H=windowsgui -s -w -X main.gitCommit=%GIT_COMMIT% -X main.versionTag=%VERSION_TAG% -X main.buildType=%BUILD_TYPE%" "%DEEJ_ROOT%\cmd"
 ECHO Done.
 GOTO DONE
```

**Comment by medusalix** [comment]
> As for the Linux scripts, leaving it up to your discretion whether you'd like the same for them.

It's unfortunately not possible to reliably determine the script's full path name on Linux. We've got `$0`, but that can be a relative path, an absolute path or just the filename depending on how the script is executed, so I'd rather leave it as it is.

**Comment by omriharel** [comment]
Thanks! I don't have any code remarks, so this seems ready to merge.

**Pull request merged**
