### PR TITLE
Add udp support

### PR DESCRIPTION
**Pull request by iamjackg**
This PR adds a UDP backend that allows users to control deej via the network. It uses the same protocol format as the serial message (minus the `\r\n` at the end of each message) and can be selected through the configuration file. All configuration options still default to serial unless the user specifically chose the UDP backend.

My specific use case is to be able to control two separate computers with a single microcontroller. I'm using an ESP32, and I'm sending data for the first few faders to one laptop, and data for the remaining faders to the other laptop.

This effectively enables anything with a working network connection to control deej, which is really cool. On the other hand, since there is no authentication, this enables _anything_ with a network connection to control deej. :stuck_out_tongue_winking_eye: I think it's an acceptable compromise since the user would have to explicitly select the UDP backend, and I think we can "market" it towards more tech-savy users anyway.

I did not include a basic sketch for this because it requires a bit more setup than just a single `.ino` file, and I only mentioned this new backend in passing in the README. I'm thinking we could maybe have a Wiki page specifically on this topic?

Let me know your thoughts!

### CODE REVIEW

**Comment by omriharel** [comment]
Hi there @iamjackg, thank you for your interest in contributing your changes back to deej!

I apologize, but currently I'm not interested in adding a TCP/IP-based networking layer to deej's main fork. I am purposely keeping it lightweight to make it as easy as possible for beginners to get started with the project, and also to avoid potential bloat for users that care about this kind of stuff.

This use-case has its merits, but isn't something that 99% of people using deej would need - which is why I think it should stay in a fork. If you're interested in discoverability for your work, I suggest reaching out through our community Discord server and submitting your build to our community showcase. That way, anyone who sees it and wants to use your work would be able to find a link there.

Please let me know your thoughts. Thank you!

**Comment by iamjackg** [comment]
I knew that was your philosophy, that's why I made the configuration default to serial. The UDP backend is not even loaded unless people specifically select it in the configuration file. I still think this is a cool option to give more advanced users, since it allows for things like wireless or battery-operated controllers and has no downsides otherwise.

The work in this PR also creates a foundation to be able to add more backends in the future, like support for MIDI devices.

That being said this is your project, so it's up to you :)

**Comment by iamjackg** [comment]
Lastly, when coupled with something like https://esphome.io/ and home-assistant.io/ this would open up an incredible amount of options, including integrating deej into your home automation setup! You could do cool stuff like automatically set all the faders to 0 when the sun goes down, or dumb stuff like changing the volume based on the temperature in your room :laughing:

I think it would be a pity to have to maintain this in a separate fork, which would need to be kept up to date with all the improvements from the main repo, especially considering that this backend is completely optional. But as I said, your project, your rules. :)

**Comment by omriharel** [comment]
I understand this latter concern, and I do appreciate the extra effort that went into making this an optional feature - however it is still not something I would want to incorporate, due to the reasons I mentioned above. The argument for creating new possibilities is totally valid, but I think that in this instance it's sort of like "just because we _can_ do something, doesn't mean we should".

**Comment by iamjackg** [comment]
Alright.

**Pull request closed without merging**
