### PR TITLE
Solution for issue #23 -- retry serial connections

### PR DESCRIPTION
**Pull request by marcuswu**
This change makes deej retry the serial connection if it is unable to connect at start up or if it disconnects after the initial connection. It solves issue #23.

Should the connection continue to fail, the attempts will exponentially back off until it reaches  100 seconds between attempts.

The changes here are fairly quick / rudimentary. I basically did the minimum necessary to get it functioning. If more is desired, lmk.

### CODE REVIEW

**Comment by Nickxsch** [comment]
@omriharel is this a decent fix/method to make the retry work? Again, I'm not a great programmer, so this looks fine to me. If possible, I'd even be happy to beta test.

**Comment by prueker** [comment]
@omriharel any chance of merging this soon to make a new release to fix the issue?

**Comment by omriharel** [comment]
Hi @marcuswu, thank you for your interest in contributing to deej!

I apologize for the delay in responding to this PR. I've been under a lot of internal stress thinking how I'd like to handle external contributions for the project, and I kept putting it off and went completely silent (both here and on #23). I realize that this reflects poorly on myself and the project, and I'll do my best to make communication a much higher priority moving forward.

I recently decided that I prefer to work on deej mostly by myself, which you can read more about in the project's contribution guidelines that I outlined [here](https://github.com/omriharel/deej/blob/master/docs/CONTRIBUTING.md).

While I'm positive that the changes you made here are high quality work (and solve the original issue), I prefer to tackle the reconnection issue alongside other improvements related to connection stability that I'm planning in the near future. I hope this is understandable, and apologies once more for the delay.

**Comment by omriharel** [comment]
cc: @Nickxsch @prueker - apologies for making you folks wait, please read my above response for context. In the meantime, I encourage you to take these changes from @marcuswu's branch. Thank you!

**Comment by Nickxsch** [comment]
As always, I understand this is a free time project and don't expect anything from you. I will try to build the fork Marcus made (google here I come!) and am looking forward to what you've got in store for the future man.

**Pull request closed without merging**
